AllCops:
  TargetRubyVersion: 2.3

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics:
  Enabled: false